version: "3.8"
services:

  nginx:
    image: nginx:alpine
    networks:
      - ingress
    deploy:
      replicas: 5 
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  ingress:
    external: true
    name: ingress-routing